version: 2.1
defaults: &defaults
  docker:
  - image: quay.io/pantheon-public/build-tools-ci:4.x
  working_directory: ~/sitedir
  environment:
    TZ: "/usr/share/zoneinfo/America/Los_Angeles"
    ADMIN_USERNAME: admin
    BUILD_TOOLS_VERSION: dev-option-for-no-force
    TERM: dumb


workflows:
  version: 2
  build_push_test:
    jobs:
      # Eventually this job should come from a CircleCI maintained orb.
      - playground/npmbuild_and_persist:
          package_lock_location: "web/wp-content/themes/stevector-sage"
          path_to_persist: "web/wp-content/themes/stevector-sage/dist"
          build_command: "npm run build:production"
      - pantheon/push:
          pre-steps:
            - checkout
            - playground/composer_install_no_dev
            - run: cd web/wp-content/themes/stevector-sage/ && composer install --no-dev --optimize-autoloader --ignore-platform-reqs
            - attach_workspace:
                at: .
          post-steps:
            - run: cd "/tmp/pantheon_repo_for_$TERMINUS_SITE" && git status
          requires:
            - playground/npmbuild_and_persist
      - playground/backstop:
          requires:
            - pantheon/push
      - playground/merge:
          requires:
             - playground/backstop
orbs:
  playground: fauxalgore/playground@dev:12
  pantheon: stevector/pantheon@dev:stevector
