defaults: &defaults
  docker:
  - image: quay.io/pantheon-public/build-tools-ci:4.x
  working_directory: ~/example_wordpress_composer
  environment:
    TZ: "/usr/share/zoneinfo/America/Los_Angeles"
    ADMIN_USERNAME: admin
    BUILD_TOOLS_VERSION: dev-master
    TERM: dumb

commands:
  setbashenv:
    description: "Copy the bash_env from the first job so that TERMINUS_ENV persists."
    steps:
    - checkout
    - attach_workspace:
        at: /tmp/workspace
    - run: cp /tmp/workspace/bash_env.txt $BASH_ENV
    - run: source $BASH_ENV
  runbackstop:
    description: ""
    steps:
    - echo "hello world"

version: 2.1
jobs:
    npmbuild:
      docker:
        - image: node:10.15.3
      steps:
        - checkout
        - run: cd web/wp-content/themes/stevector-sage && npm ci
        - run: cd web/wp-content/themes/stevector-sage && npm run build:production

        - persist_to_workspace:
            root: .
            paths:
              - web/wp-content/themes/stevector-sage/dist
    # @todo: common initialization, maybe
    build:
      <<: *defaults
      steps:
      - checkout
      - run: /build-tools-ci/scripts/set-environment
      - attach_workspace:
          at: .

      - restore_cache:
          keys:
          - composer
      - run: composer -n build-assets
      - save_cache:
          key: composer
          paths:
          - $HOME/.composer/cache
      - run: terminus -n auth:login --machine-token="$TERMINUS_TOKEN"

      - run:
          name: Delete old Multidevs and other prepare steps
          command: terminus -n build:env:delete:ci "$TERMINUS_SITE" --keep=2 --yes      #./vendor/pantheon-systems/docker-build-tools-ci/scripts/from-example-drops-8-composer/ci-scripts/01-prepare

      - run:
          name: deploy
          command: |
            # Create a new multidev site to test on
            terminus -n env:wake "$TERMINUS_SITE.dev"
            terminus -n build:env:create "$TERMINUS_SITE.dev" "$TERMINUS_ENV" --yes --clone-content

      - run: cp $BASH_ENV bash_env.txt
      - persist_to_workspace:
          root: .
          paths:
          - bash_env.txt

    backstop:
      docker:
      - image: backstopjs/backstopjs:3.9.5
      working_directory: ~/example_drops_8_composer
      steps:
      - setbashenv
      - run: cd backstop && ./run-backstop.sh
      - store_artifacts:
          path: /tmp/artifacts
          destination: artifact
      - run: ./backstop/report-backstop.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - npmbuild
      - build:
          requires:
            - npmbuild
      - backstop:
          requires:
            - build
