version: 2.1
workflows:
  version: 2
  build_push_test:
    jobs:
      # Eventually this job should come from a CircleCI maintained orb.
      - playground/npmbuild_and_persist:
          package_lock_location: "web/wp-content/themes/stevector-sage"
          path_to_persist: "web/wp-content/themes/stevector-sage/dist"
          build_command: "npm run build:production"
          post-steps:
          - slack/notify:
              author_name: 'CircleCI status'
              include_job_number_field: false
              mentions: "UJQVBGN9G"

      - approve_npm:
          type: approval
          pre-steps:
            - slack/approval:
              message: "hey, could you sign off on this npm build real quick?"
              mentions: "UJQVBGN9G"
              requires:
          requires:
          - playground/npmbuild_and_persist
      - pantheon/push:
          checkout: false
          pre-steps:
            - checkout
            - playground/composer_install_no_dev
            - run: cd web/wp-content/themes/stevector-sage/ && composer install --no-dev --optimize-autoloader --ignore-platform-reqs
            - run: composer prepare-for-pantheon
            - attach_workspace:
                at: .
          post-steps:
            - run: cd "/tmp/pantheon_repo" && git status
            - run: echo "Testing CI on master branch"
          requires:
            - playground/npmbuild_and_persist
      - playground/backstop:
          requires:
            - pantheon/push
      - approve_dev_env:
          type: approval
          requires:
          - playground/backstop
      - deploy_to_test:
          requires:
          - approve_dev_env
          filters:
            branches:
              only: "master"

orbs:
  # fauxalgore is a joke username where I publish experimental
  # code. https://github.com/fauxalgore/orbs This repo is a playground
  # for Orbs that might become stable elsewhere.
  playground: fauxalgore/playground@0.0.2
  pantheon: pantheon-systems/pantheon@0.0.2
  slack: circleci/slack@2.5.1

jobs:
  deploy_to_test:
    docker:
    - image: quay.io/pantheon-public/build-tools-ci:5.x
    steps:
    - run:
        name: Authenticate with Pantheon's CLI using a machine token
        command: terminus -n auth:login --machine-token="$TERMINUS_TOKEN"
    - run: terminus env:deploy $TERMINUS_SITE.test --note="automatic deployment from CI"  --sync-content --cc
#  slack_notify:
#    executor: alpine
#    steps:
#      - slack/notify
