workflows:
  version: 2
  build_and_test:
    jobs:
      - npmbuild
      - playground/build:
          requires:
            - npmbuild
      - playground/backstop:
          requires:
            - playground/build


version: 2.1
jobs:
    npmbuild:
      docker:
        - image: node:10.15.3
      steps:
        - checkout
        - inline_example/npmci_and_cache:
            package_lock_location: "web/wp-content/themes/stevector-sage"
            path_to_persist: "web/wp-content/themes/stevector-sage/dist"
            build_command: "npm run build:production"


orbs:
  playground: fauxalgore/playground@dev:second
  inline_example:
    commands:
      npmci_and_cache:
        parameters:
          path_to_persist:
            type: string
          package_lock_location:
            type: string
          build_command:
            type: string
        steps:
          - run: echo "hello <<parameters.package_lock_location>>, from the inline command"
          - restore_cache:
              keys:
                # when lock file changes, use increasingly general patterns to restore cache
                - node-v1-{{ .Branch }}-{{ checksum "<<parameters.package_lock_location>>/package-lock.json" }}
                - node-v1-{{ .Branch }}-
                - node-v1-
          - run: cd <<parameters.package_lock_location>> && npm ci
        - save_cache:
            paths:
              - /root/.npm
            key: node-v1-{{ .Branch }}-{{ checksum "<<parameters.package_lock_location>>/package-lock.json" }}
        - run: cd <<parameters.package_lock_location>> && <<parameters.build_command>>
        - persist_to_workspace:
            root: .
            paths:
              - <<parameters.path_to_persist>>
