version: 2.1
workflows:
  version: 2
  build_push_test:
    jobs:
      # Eventually this job should come from a CircleCI maintained orb.
      - playground/npmbuild_and_persist:
          package_lock_location: "web/wp-content/themes/stevector-sage"
          path_to_persist: "web/wp-content/themes/stevector-sage/dist"
          build_command: "npm run build:production"
      - pantheon/push:
          checkout: false
          pre-steps:
            - checkout
            - playground/composer_install_no_dev
            - run: cd web/wp-content/themes/stevector-sage/ && composer install --no-dev --optimize-autoloader --ignore-platform-reqs
            - run: composer prepare-for-pantheon
            - attach_workspace:
                at: .
          post-steps:
            - run: cd "/tmp/pantheon_repo" && git status
          requires:
            - playground/npmbuild_and_persist

      - playground2/npmbuild_and_persist:
          package_lock_location: "frontity"
          path_to_persist: "frontity/build"
          build_command: "npm run build"
#           requires:
#             - pantheon/push
          pre-steps:
            - playground/setbashenv
      - deploy_cloud_function:
           requires:
             - playground2/npmbuild_and_persist

      - playground/backstop:
          requires:
            - deploy_cloud_function

      - backup_test_env:
          requires:
          - playground/backstop
          filters:
            branches:
              only: "master"
      - slack/approval-notification:
          message: "hey, could you look at https://dev-stevector-composer.pantheonsite.io/ and sign off on a deployment to Test real quick?"
          mentions: "UJQVBGN9G"
          requires:
          - playground/backstop
          filters:
            branches:
              only: "master"
          pre-steps:
            # Warm the cache in the environment.
            - run: curl https://dev-stevector-composer.pantheonsite.io/
      - approve_dev_env:
          type: approval
          requires:
          - playground/backstop
          filters:
            branches:
              only: "master"
      - deploy_to_test:
          requires:
          - approve_dev_env
          - backup_test_env
          filters:
            branches:
              only: "master"
      - slack/approval-notification:
          message: "hey, could you look at https://test-stevector-composer.pantheonsite.io/ and sign off on a deployment to Live real quick?"
          mentions: "UJQVBGN9G"
          requires:
          - deploy_to_test
          filters:
            branches:
              only: "master"
          pre-steps:
            # Warm the cache in the environment.
            - run: curl https://test-stevector-composer.pantheonsite.io/
      - approve_test_env:
          type: approval
          requires:
          - deploy_to_test
          filters:
            branches:
              only: "master"
      - deploy_to_live:
          requires:
          - approve_test_env
          filters:
            branches:
              only: "master"

orbs:
  # fauxalgore is a joke username where I publish experimental
  # code. https://github.com/fauxalgore/orbs This repo is a playground
  # for Orbs that might become stable elsewhere.
  playground: fauxalgore/playground@0.0.2
  playground2: fauxalgore/playground@0.0.2
  pantheon: pantheon-systems/pantheon@0.1.0
  # https://circleci.com/orbs/registry/orb/circleci/slack
  slack: circleci/slack@2.5.1
  gcp-cli: circleci/gcp-cli@1.0.0

jobs:
  deploy_cloud_function:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - attach_workspace:
          at: .
 #     - playground/setbashenv
      - run: ls -al
      - run: cd frontity/build && ls -al
      - run:
          name: Login to gcloud
          command: |
            echo $GCLOUD_SERVICE_KEY_RESTRICTED | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}

      - run:
          name: deploy
          # @todo make a variable for serverlessplayground and runtime, and probably everything in gcloud functions deploy.
          command: |
            TERMINUS_ENV=pr-79 && gcloud functions deploy ${TERMINUS_SITE}--${TERMINUS_ENV}  --project=serverlessplayground --runtime=nodejs10 --trigger-http  --allow-unauthenticated  --entry-point=default --source=frontity/build --set-env-vars="TERMINUS_SITE=${TERMINUS_SITE},TERMINUS_ENV=${TERMINUS_ENV}"
  backup_test_env:
    docker:
    - image: quay.io/pantheon-public/build-tools-ci:5.x
    steps:
    - run:
        name: Authenticate with Pantheon's CLI using a machine token
        command: terminus -n auth:login --machine-token="$TERMINUS_TOKEN"
    - run: terminus backup:create $TERMINUS_SITE.test
  deploy_to_test:
    docker:
    - image: quay.io/pantheon-public/build-tools-ci:5.x
    steps:
    - run:
        name: Authenticate with Pantheon's CLI using a machine token
        command: terminus -n auth:login --machine-token="$TERMINUS_TOKEN"
    - run: echo "I should update the --note field to account for commit messages"
    - run: terminus env:deploy $TERMINUS_SITE.test --note="automatic deployment from CI"  --sync-content --cc
    # This cache clear shouldn't be necessary but run it just to be safe.
    - run: terminus env:clear-cache $TERMINUS_SITE.test
  deploy_to_live:
    docker:
    - image: quay.io/pantheon-public/build-tools-ci:5.x
    steps:
    - run:
        name: Authenticate with Pantheon's CLI using a machine token
        command: terminus -n auth:login --machine-token="$TERMINUS_TOKEN"
    - run: echo "I should update the --note field to account for commit messages"
    - run: terminus env:deploy $TERMINUS_SITE.live --note="automatic deployment from CI"  --sync-content --cc
    # This cache clear shouldn't be necessary but run it just to be safe.
    - run: terminus env:clear-cache $TERMINUS_SITE.live    
