version: 2.1
workflows:
  version: 2
  build_push_test:
    jobs:
      # Eventually this job should come from a CircleCI maintained orb.
      - playground/npmbuild_and_persist:
          package_lock_location: "web/wp-content/themes/stevector-sage"
          path_to_persist: "web/wp-content/themes/stevector-sage/dist"
          build_command: "npm run build:production"
      - pantheon/push:
          checkout: false
          pre-steps:
            - checkout
            - playground/composer_install_no_dev
            - run: cd web/wp-content/themes/stevector-sage/ && composer install --no-dev --optimize-autoloader --ignore-platform-reqs
            - run: composer prepare-for-pantheon
            - attach_workspace:
                at: .
          post-steps:
            - run: cd "/tmp/pantheon_repo" && git status
            - run: echo "Testing CI on master branch"
          requires:
            - playground/npmbuild_and_persist
      - playground/backstop:
          requires:
            - pantheon/push
      - approve_dev_env:
          type: approval
          requires:
          - pantheon/push
      - deploy_to_test:
          requires:
          - approve_dev_env
          filters:
            branches:
              only: "master"

orbs:
  playground: fauxalgore/playground@0.0.2
  pantheon: pantheon-systems/pantheon@0.0.2

jobs:
  deploy_to_test:
    docker:
    - image: quay.io/pantheon-public/build-tools-ci:5.x
    steps:
    - run: terminus env:deploy $TERMINUS_SITE.test --note="automatic deployment from CI"  --sync-content --cc
