workflows:
  version: 2
  build_and_test:
    jobs:
      - npmbuild
      - fauxalgore/build:
          requires:
            - npmbuild
      - fauxalgore/backstop:
          requires:
            - buil


version: 2.1
jobs:
    npmbuild:
      docker:
        - image: node:10.15.3
      steps:
        - checkout
        - restore_cache:
            keys:
              # when lock file changes, use increasingly general patterns to restore cache
              - node-v1-{{ .Branch }}-{{ checksum "web/wp-content/themes/stevector-sage/package-lock.json" }}
              - node-v1-{{ .Branch }}-
              - node-v1-
        - run: cd web/wp-content/themes/stevector-sage && npm ci
        - save_cache:
            paths:
              - /root/.npm
            key: node-v1-{{ .Branch }}-{{ checksum "web/wp-content/themes/stevector-sage/package-lock.json" }}

        - run: cd web/wp-content/themes/stevector-sage && npm run build:production

        - persist_to_workspace:
            root: .
            paths:
              - web/wp-content/themes/stevector-sage/dist


orbs:
  fauxalgore: fauxalgore/playground@dev:first
