workflows:
  version: 2
  build_and_test:
    jobs:
      - npmbuild
      - playground/build:
          requires:
            - npmbuild
      - playground/backstop:
          requires:
            - playground/build


version: 2.1
jobs:
    npmbuild:
      docker:
        - image: node:10.15.3
      steps:
        - checkout
        - inline_example/npmci_and_cache:
            package_lock_location: "web/wp-content/themes/stevector-sage"

        # - restore_cache:
        #     keys:
        #       # when lock file changes, use increasingly general patterns to restore cache
        #       - node-v1-{{ .Branch }}-{{ checksum "web/wp-content/themes/stevector-sage/package-lock.json" }}
        #       - node-v1-{{ .Branch }}-
        #       - node-v1-
        # - run: cd web/wp-content/themes/stevector-sage && npm ci
        - save_cache:
            paths:
              - /root/.npm
            key: node-v1-{{ .Branch }}-{{ checksum "web/wp-content/themes/stevector-sage/package-lock.json" }}

        - run: cd web/wp-content/themes/stevector-sage && npm run build:production

        - persist_to_workspace:
            root: .
            paths:
              - web/wp-content/themes/stevector-sage/dist


orbs:
  playground: fauxalgore/playground@dev:second
  inline_example:
    commands:
      npmci_and_cache:
        parameters:
          package_lock_location:
            type: string
        steps:
          - run: echo "hello <<parameters.package_lock_location>>, from the inline command"
          - restore_cache:
              keys:
                # when lock file changes, use increasingly general patterns to restore cache
                - node-v1-{{ .Branch }}-{{ checksum "<<parameters.package_lock_location>>/package-lock.json" }}
                - node-v1-{{ .Branch }}-
                - node-v1-
          - run: cd <<parameters.package_lock_location>> && npm ci
